# Caso de uso: Uber

**Objetivo:** Predecir si en un requerimiento habrá algún chofer disponible

In [1]:
# Librerías

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
pd.set_option('display.max_columns', None)
warnings.filterwarnings("ignore")

In [2]:
# Cargar datos

data = pd.read_csv("../data/ncr_ride_bookings.csv")
data.head(2)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI

In [3]:
# TODO: Poner en módulo utils
def limpiar_columnas(df):
    df.columns = [i.replace(" ","_").lower() for i in df.columns]
    return df

data = limpiar_columnas(data)
data["date"] = pd.to_datetime(data["date"], errors="raise").dt.date
data["time"] = pd.to_datetime(data["time"], errors="raise").dt.time

In [4]:
# TODO: Poner en un archivo config
import pandera as pa
from typing import Optional
import datetime as dt

# Creamos un esquema utilizando la API de Schema en lugar de SchemaModel

def create_uber_ride_schema():
    """
    Crea un esquema para validar el DataFrame de viajes de Uber.
    """
    # Definir las columnas obligatorias (no nulas)
    schema = pa.DataFrameSchema({
        "date": pa.Column(
            dtype=object,  
            nullable=False,
            coerce=True,
            checks=[pa.Check(lambda x: isinstance(x, dt.date), element_wise=True)]
        ),
        "time": pa.Column(
            dtype=object, 
            nullable=False,
            coerce=True,
            checks=[pa.Check(lambda x: isinstance(x, dt.time), element_wise=True)]
        ),
        "booking_id": pa.Column(
            dtype=str,
            nullable=False,
            coerce=True
        ),
        "booking_status": pa.Column(
            dtype=str,
            nullable=False,
            coerce=True
        ),
        "customer_id": pa.Column(
            dtype=str,
            nullable=False,
            coerce=True
        ),
        "vehicle_type": pa.Column(
            dtype=str,
            nullable=False,
            coerce=True
        ),
    
        "pickup_location": pa.Column(
            dtype=str,
            nullable=True,
            coerce=True
        ),
        "drop_location": pa.Column(
            dtype=str,
            nullable=True,
            coerce=True
        ),
        "avg_vtat": pa.Column(
            dtype=float,
            nullable=True,
            coerce=True
        ),
        "avg_ctat": pa.Column(
            dtype=float,
            nullable=True,
            coerce=True
        ),
        "cancelled_rides_by_customer": pa.Column(
            dtype=float,  
            nullable=True,
            coerce=True
        ),
        "reason_for_cancelling_by_customer": pa.Column(
            dtype=str,
            nullable=True,
            coerce=True
        ),
        "cancelled_rides_by_driver": pa.Column(
            dtype=float,
            nullable=True,
            coerce=True
        ),
        "driver_cancellation_reason": pa.Column(
            dtype=str,
            nullable=True,
            coerce=True
        ),
        "incomplete_rides": pa.Column(
            dtype=float,
            nullable=True,
            coerce=True
        ),
        "incomplete_rides_reason": pa.Column(
            dtype=str,
            nullable=True,
            coerce=True
        ),
        "booking_value": pa.Column(
            dtype=float,
            nullable=True,
            coerce=True
        ),
        "ride_distance": pa.Column(
            dtype=float,
            nullable=True,
            coerce=True
        ),
        "driver_ratings": pa.Column(
            dtype=float,
            nullable=True,
            coerce=True
        ),
        "customer_rating": pa.Column(
            dtype=float,
            nullable=True,
            coerce=True
        ),
        "payment_method": pa.Column(
            dtype=str,
            nullable=True,
            coerce=True
        ),
 
    }, strict=True)  # No permite columnas extra
    
    return schema

# Crear instancia del esquema
UberRideSchema = create_uber_ride_schema()

In [5]:
data = UberRideSchema.validate(data)

In [6]:
# Crear target
# Aquellos viajes donde no haya un chofer asignado
# Considerar solamente aquellos viajes en los que no hay chofer
# booking_status = "No driver found"
# TODO: Agregar esta función en el módulo utils

def crear_target(df: pd.DataFrame) -> pd.DataFrame:
    df["target"] = np.where(df["booking_status"]=="No Driver Found",1,0)
    return df

data = crear_target(data)

In [7]:
# Algunas métricas
print(data.shape)

# Rango de fechas del dataset

print(data["date"].min())
print(data["date"].max())

(150000, 22)
2024-01-01
2024-12-30

In [8]:
data.head(1)

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,avg_vtat,avg_ctat,cancelled_rides_by_customer,reason_for_cancelling_by_customer,cancelled_rides_by_driver,driver_cancellation_reason,incomplete_rides,incomplete_rides_reason,booking_value,ride_distance,driver_ratings,customer_rating,payment_method,target
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [9]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np

# TODO: Poner en modulo feature engineering
def crear_embeddings(
        df: pd.DataFrame,
        col_name: str,
        n_embeddings: int
) -> pd.DataFrame:
    s = df[col_name].astype("string")

    cats = pd.Categorical(s)                 # categorías a partir de los datos
    codes = cats.codes + 1                   # -1 (NaN) -> 0 después de +1
    codes = np.where(cats.codes < 0, 0, codes)  # por claridad
    idx = torch.tensor(codes, dtype=torch.long)

    num_cats = len(cats.categories)          # K
    emb = nn.Embedding(num_embeddings=num_cats + 1, embedding_dim=n_embeddings, padding_idx=0)

    E = emb(idx) 
    n_embeddings_array = E.detach().cpu().numpy()
    df_embeddings = pd.DataFrame(
        n_embeddings_array,
        index = df.index
    )
    df_embeddings.columns = [f"{col_name}_{n}" for n in range(n_embeddings)]
    return pd.concat([df, df_embeddings], axis = 1)

In [10]:
data = crear_embeddings(data, "pickup_location", 32)
data = crear_embeddings(data, "drop_location", 32)

In [11]:
# Train test split

vars = [
    f"pickup_location_{i}" for i in range(32)
] + [
    f"drop_location_{i}" for i in range(32)
]

target = ["target"]

x = data[vars]
y = data[target]

In [12]:
# train test split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=123)

In [13]:
from catboost import CatBoostClassifier

modelo = CatBoostClassifier(random_state=123)

modelo.fit(x_train, y_train)

Learning rate set to 0.079569
0:	learn: 0.6095051	total: 63.9ms	remaining: 1m 3s
1:	learn: 0.5420017	total: 70.3ms	remaining: 35.1s
2:	learn: 0.4875178	total: 76.3ms	remaining: 25.4s
3:	learn: 0.4436233	total: 82ms	remaining: 20.4s
4:	learn: 0.4082481	total: 87.3ms	remaining: 17.4s
5:	learn: 0.3796344	total: 93.1ms	remaining: 15.4s
6:	learn: 0.3565231	total: 98.7ms	remaining: 14s
7:	learn: 0.3378079	total: 104ms	remaining: 12.9s
8:	learn: 0.3226109	total: 110ms	remaining: 12.1s
9:	learn: 0.3102614	total: 115ms	remaining: 11.4s
10:	learn: 0.3001640	total: 121ms	remaining: 10.8s
11:	learn: 0.2919004	total: 126ms	remaining: 10.4s
12:	learn: 0.2851347	total: 132ms	remaining: 10s
13:	learn: 0.2795767	total: 137ms	remaining: 9.67s
14:	learn: 0.2749898	total: 143ms	remaining: 9.38s
15:	learn: 0.2711763	total: 149ms	remaining: 9.14s
16:	learn: 0.2680333	total: 154ms	remaining: 8.93s
17:	learn: 0.2654237	total: 160ms	remaining: 8.73s
18:	learn: 0.2632808	total: 165ms	remaining: 8.5s
19:	learn: 0.2614703	total: 170ms	remaining: 8.35s
20:	learn: 0.2599562	total: 176ms	remaining: 8.21s
21:	learn: 0.2587016	total: 181ms	remaining: 8.06s
22:	learn: 0.2576270	total: 188ms	remaining: 7.97s
23:	learn: 0.2567442	total: 193ms	remaining: 7.85s
24:	learn: 0.2559935	total: 199ms	remaining: 7.77s
25:	learn: 0.2553565	total: 205ms	remaining: 7.69s
26:	learn: 0.2548315	total: 211ms	remaining: 7.61s
27:	learn: 0.2543815	total: 218ms	remaining: 7.57s
28:	learn: 0.2540022	total: 223ms	remaining: 7.46s
29:	learn: 0.2536844	total: 229ms	remaining: 7.39s
30:	learn: 0.2533755	total: 234ms	remaining: 7.33s
31:	learn: 0.2531327	total: 240ms	remaining: 7.27s
32:	learn: 0.2529234	total: 246ms	remaining: 7.2s
33:	learn: 0.2527413	total: 251ms	remaining: 7.13s
34:	learn: 0.2525787	total: 257ms	remaining: 7.09s
35:	learn: 0.2524308	total: 263ms	remaining: 7.03s
36:	learn: 0.2522957	total: 268ms	remaining: 6.98s
37:	learn: 0.2521772	total: 274ms	remaining: 6.93s
38:	learn: 0.2520747	total: 280ms	remaining: 6.89s
39:	learn: 0.2519617	total: 285ms	remaining: 6.84s
40:	learn: 0.2518805	total: 291ms	remaining: 6.8s
41:	learn: 0.2518010	total: 296ms	remaining: 6.76s
42:	learn: 0.2517127	total: 302ms	remaining: 6.72s
43:	learn: 0.2516474	total: 308ms	remaining: 6.68s
44:	learn: 0.2515841	total: 313ms	remaining: 6.64s
45:	learn: 0.2515123	total: 319ms	remaining: 6.61s
46:	learn: 0.2514324	total: 324ms	remaining: 6.57s
47:	learn: 0.2513755	total: 330ms	remaining: 6.55s
48:	learn: 0.2513050	total: 336ms	remaining: 6.52s
49:	learn: 0.2512353	total: 341ms	remaining: 6.48s
50:	learn: 0.2511795	total: 346ms	remaining: 6.45s
51:	learn: 0.2511229	total: 352ms	remaining: 6.42s
52:	learn: 0.2510560	total: 358ms	remaining: 6.39s
53:	learn: 0.2510023	total: 363ms	remaining: 6.36s
54:	learn: 0.2509614	total: 369ms	remaining: 6.33s
55:	learn: 0.2509065	total: 378ms	remaining: 6.37s
56:	learn: 0.2508586	total: 384ms	remaining: 6.35s
57:	learn: 0.2508117	total: 390ms	remaining: 6.33s
58:	learn: 0.2507634	total: 395ms	remaining: 6.3s
59:	learn: 0.2507124	total: 401ms	remaining: 6.28s
60:	learn: 0.2506549	total: 407ms	remaining: 6.26s
61:	learn: 0.2505915	total: 417ms	remaining: 6.31s
62:	learn: 0.2505410	total: 422ms	remaining: 6.28s
63:	learn: 0.2504775	total: 428ms	remaining: 6.26s
64:	learn: 0.2504237	total: 434ms	remaining: 6.24s
65:	learn: 0.2503786	total: 439ms	remaining: 6.21s
66:	learn: 0.2503442	total: 444ms	remaining: 6.18s
67:	learn: 0.2503048	total: 449ms	remaining: 6.15s
68:	learn: 0.2502539	total: 474ms	remaining: 6.4s
69:	learn: 0.2501943	total: 486ms	remaining: 6.45s
70:	learn: 0.2501716	total: 490ms	remaining: 6.42s
71:	learn: 0.2501203	total: 496ms	remaining: 6.39s
72:	learn: 0.2500854	total: 502ms	remaining: 6.37s
73:	learn: 0.2500406	total: 508ms	remaining: 6.36s
74:	learn: 0.2499763	total: 515ms	remaining: 6.35s
75:	learn: 0.2499308	total: 522ms	remaining: 6.34s
76:	learn: 0.2498816	total: 530ms	remaining: 6.36s
77:	learn: 0.2498292	total: 538ms	remaining: 6.36s
78:	learn: 0.2497811	total: 545ms	remaining: 6.36s
79:	learn: 0.2497307	total: 553ms	remaining: 6.36s
80:	learn: 0.2496828	total: 563ms	remaining: 6.39s
81:	learn: 0.2496395	total: 570ms	remaining: 6.38s
82:	learn: 0.2495914	total: 576ms	remaining: 6.37s
83:	learn: 0.2495361	total: 583ms	remaining: 6.36s
84:	learn: 0.2494813	total: 589ms	remaining: 6.34s
85:	learn: 0.2494546	total: 596ms	remaining: 6.33s
86:	learn: 0.2494116	total: 602ms	remaining: 6.32s
87:	learn: 0.2493602	total: 609ms	remaining: 6.31s
88:	learn: 0.2492994	total: 616ms	remaining: 6.3s
89:	learn: 0.2492577	total: 622ms	remaining: 6.28s
90:	learn: 0.2492130	total: 628ms	remaining: 6.27s
91:	learn: 0.2491690	total: 634ms	remaining: 6.26s
92:	learn: 0.2491150	total: 641ms	remaining: 6.25s
93:	learn: 0.2490682	total: 648ms	remaining: 6.25s
94:	learn: 0.2490358	total: 654ms	remaining: 6.23s
95:	learn: 0.2489779	total: 661ms	remaining: 6.22s
96:	learn: 0.2489231	total: 667ms	remaining: 6.21s
97:	learn: 0.2488702	total: 673ms	remaining: 6.2s
98:	learn: 0.2488102	total: 679ms	remaining: 6.18s
99:	learn: 0.2487594	total: 685ms	remaining: 6.17s
100:	learn: 0.2487413	total: 692ms	remaining: 6.16s
101:	learn: 0.2486945	total: 698ms	remaining: 6.15s
102:	learn: 0.2486442	total: 706ms	remaining: 6.14s
103:	learn: 0.2486071	total: 712ms	remaining: 6.13s
104:	learn: 0.2485556	total: 718ms	remaining: 6.12s
105:	learn: 0.2485030	total: 726ms	remaining: 6.12s
106:	learn: 0.2484560	total: 734ms	remaining: 6.12s
107:	learn: 0.2484172	total: 741ms	remaining: 6.12s
108:	learn: 0.2483669	total: 749ms	remaining: 6.12s
109:	learn: 0.2483166	total: 756ms	remaining: 6.11s
110:	learn: 0.2482712	total: 763ms	remaining: 6.11s
111:	learn: 0.2482222	total: 769ms	remaining: 6.1s
112:	learn: 0.2481696	total: 775ms	remaining: 6.08s
113:	learn: 0.2481156	total: 781ms	remaining: 6.07s
114:	learn: 0.2480920	total: 786ms	remaining: 6.05s
115:	learn: 0.2480453	total: 792ms	remaining: 6.03s
116:	learn: 0.2479948	total: 798ms	remaining: 6.03s
117:	learn: 0.2479501	total: 806ms	remaining: 6.03s
118:	learn: 0.2479089	total: 812ms	remaining: 6.01s
119:	learn: 0.2478680	total: 818ms	remaining: 6s
120:	learn: 0.2478253	total: 824ms	remaining: 5.98s
121:	learn: 0.2477770	total: 830ms	remaining: 5.97s
122:	learn: 0.2477521	total: 835ms	remaining: 5.95s
123:	learn: 0.2477182	total: 841ms	remaining: 5.94s
124:	learn: 0.2476874	total: 846ms	remaining: 5.92s
125:	learn: 0.2476358	total: 852ms	remaining: 5.91s
126:	learn: 0.2475887	total: 858ms	remaining: 5.89s
127:	learn: 0.2475369	total: 864ms	remaining: 5.88s
128:	learn: 0.2474716	total: 870ms	remaining: 5.88s
129:	learn: 0.2474351	total: 876ms	remaining: 5.86s
130:	learn: 0.2473850	total: 881ms	remaining: 5.85s
131:	learn: 0.2473519	total: 887ms	remaining: 5.83s
132:	learn: 0.2473109	total: 893ms	remaining: 5.82s
133:	learn: 0.2472632	total: 898ms	remaining: 5.8s
134:	learn: 0.2472068	total: 904ms	remaining: 5.79s
135:	learn: 0.2471443	total: 910ms	remaining: 5.78s
136:	learn: 0.2470866	total: 916ms	remaining: 5.77s
137:	learn: 0.2470520	total: 921ms	remaining: 5.75s
138:	learn: 0.2470141	total: 927ms	remaining: 5.74s
139:	learn: 0.2469730	total: 932ms	remaining: 5.72s
140:	learn: 0.2469322	total: 938ms	remaining: 5.71s
141:	learn: 0.2468784	total: 944ms	remaining: 5.7s
142:	learn: 0.2468462	total: 949ms	remaining: 5.68s
143:	learn: 0.2468018	total: 954ms	remaining: 5.67s
144:	learn: 0.2467607	total: 960ms	remaining: 5.66s
145:	learn: 0.2467135	total: 966ms	remaining: 5.65s
146:	learn: 0.2466601	total: 971ms	remaining: 5.64s
147:	learn: 0.2466175	total: 977ms	remaining: 5.62s
148:	learn: 0.2465778	total: 982ms	remaining: 5.61s
149:	learn: 0.2465454	total: 988ms	remaining: 5.6s
150:	learn: 0.2464969	total: 995ms	remaining: 5.59s
151:	learn: 0.2464294	total: 1s	remaining: 5.58s
152:	learn: 0.2463702	total: 1s	remaining: 5.57s
153:	learn: 0.2463105	total: 1.01s	remaining: 5.55s
154:	learn: 0.2462507	total: 1.02s	remaining: 5.54s
155:	learn: 0.2462146	total: 1.02s	remaining: 5.53s
156:	learn: 0.2461654	total: 1.03s	remaining: 5.52s
157:	learn: 0.2461126	total: 1.03s	remaining: 5.51s
158:	learn: 0.2460867	total: 1.04s	remaining: 5.5s
159:	learn: 0.2460342	total: 1.04s	remaining: 5.48s
160:	learn: 0.2459935	total: 1.05s	remaining: 5.47s
161:	learn: 0.2459535	total: 1.05s	remaining: 5.46s
162:	learn: 0.2459232	total: 1.06s	remaining: 5.45s
163:	learn: 0.2458834	total: 1.06s	remaining: 5.43s
164:	learn: 0.2458573	total: 1.07s	remaining: 5.42s
165:	learn: 0.2458264	total: 1.07s	remaining: 5.4s
166:	learn: 0.2457829	total: 1.08s	remaining: 5.39s
167:	learn: 0.2457435	total: 1.09s	remaining: 5.38s
168:	learn: 0.2457010	total: 1.09s	remaining: 5.37s
169:	learn: 0.2456764	total: 1.1s	remaining: 5.36s
170:	learn: 0.2456253	total: 1.1s	remaining: 5.35s
171:	learn: 0.2455835	total: 1.11s	remaining: 5.34s
172:	learn: 0.2455332	total: 1.11s	remaining: 5.33s
173:	learn: 0.2454805	total: 1.12s	remaining: 5.32s
174:	learn: 0.2454486	total: 1.13s	remaining: 5.32s
175:	learn: 0.2454155	total: 1.13s	remaining: 5.31s
176:	learn: 0.2453500	total: 1.14s	remaining: 5.3s
177:	learn: 0.2452807	total: 1.15s	remaining: 5.29s
178:	learn: 0.2452330	total: 1.15s	remaining: 5.28s
179:	learn: 0.2451743	total: 1.16s	remaining: 5.27s
180:	learn: 0.2451267	total: 1.16s	remaining: 5.26s
181:	learn: 0.2451116	total: 1.17s	remaining: 5.24s
182:	learn: 0.2450500	total: 1.17s	remaining: 5.23s
183:	learn: 0.2450239	total: 1.18s	remaining: 5.22s
184:	learn: 0.2449783	total: 1.18s	remaining: 5.21s
185:	learn: 0.2449124	total: 1.19s	remaining: 5.2s
186:	learn: 0.2448743	total: 1.19s	remaining: 5.19s
187:	learn: 0.2448402	total: 1.2s	remaining: 5.18s
188:	learn: 0.2447799	total: 1.21s	remaining: 5.17s
189:	learn: 0.2447102	total: 1.21s	remaining: 5.17s
190:	learn: 0.2446775	total: 1.22s	remaining: 5.16s
191:	learn: 0.2446300	total: 1.22s	remaining: 5.15s
192:	learn: 0.2445678	total: 1.23s	remaining: 5.14s
193:	learn: 0.2445176	total: 1.23s	remaining: 5.13s
194:	learn: 0.2444360	total: 1.24s	remaining: 5.12s
195:	learn: 0.2443699	total: 1.25s	remaining: 5.11s
196:	learn: 0.2443355	total: 1.25s	remaining: 5.1s
197:	learn: 0.2442962	total: 1.26s	remaining: 5.09s
198:	learn: 0.2442483	total: 1.26s	remaining: 5.08s
199:	learn: 0.2441917	total: 1.27s	remaining: 5.07s
200:	learn: 0.2441589	total: 1.27s	remaining: 5.06s
201:	learn: 0.2440939	total: 1.28s	remaining: 5.06s
202:	learn: 0.2440713	total: 1.28s	remaining: 5.04s
203:	learn: 0.2440221	total: 1.29s	remaining: 5.03s
204:	learn: 0.2439568	total: 1.29s	remaining: 5.02s
205:	learn: 0.2439074	total: 1.3s	remaining: 5.01s
206:	learn: 0.2438513	total: 1.31s	remaining: 5s
207:	learn: 0.2437842	total: 1.31s	remaining: 5s
208:	learn: 0.2437266	total: 1.32s	remaining: 4.99s
209:	learn: 0.2436678	total: 1.32s	remaining: 4.98s
210:	learn: 0.2436324	total: 1.33s	remaining: 4.97s
211:	learn: 0.2435950	total: 1.33s	remaining: 4.96s
212:	learn: 0.2435557	total: 1.34s	remaining: 4.95s
213:	learn: 0.2435298	total: 1.34s	remaining: 4.94s
214:	learn: 0.2434790	total: 1.35s	remaining: 4.93s
215:	learn: 0.2434454	total: 1.35s	remaining: 4.92s
216:	learn: 0.2434153	total: 1.36s	remaining: 4.91s
217:	learn: 0.2433651	total: 1.36s	remaining: 4.9s
218:	learn: 0.2432965	total: 1.37s	remaining: 4.89s
219:	learn: 0.2432431	total: 1.38s	remaining: 4.88s
220:	learn: 0.2431829	total: 1.38s	remaining: 4.88s
221:	learn: 0.2431207	total: 1.39s	remaining: 4.87s
222:	learn: 0.2430821	total: 1.39s	remaining: 4.86s
223:	learn: 0.2430444	total: 1.4s	remaining: 4.85s
224:	learn: 0.2429606	total: 1.4s	remaining: 4.84s
225:	learn: 0.2429134	total: 1.41s	remaining: 4.83s
226:	learn: 0.2428438	total: 1.42s	remaining: 4.82s
227:	learn: 0.2428074	total: 1.42s	remaining: 4.82s
228:	learn: 0.2427599	total: 1.43s	remaining: 4.81s
229:	learn: 0.2427326	total: 1.43s	remaining: 4.8s
230:	learn: 0.2427014	total: 1.44s	remaining: 4.79s
231:	learn: 0.2426513	total: 1.45s	remaining: 4.78s
232:	learn: 0.2425780	total: 1.45s	remaining: 4.78s
233:	learn: 0.2425345	total: 1.46s	remaining: 4.77s
234:	learn: 0.2424876	total: 1.46s	remaining: 4.76s
235:	learn: 0.2424585	total: 1.47s	remaining: 4.75s
236:	learn: 0.2424150	total: 1.47s	remaining: 4.74s
237:	learn: 0.2423881	total: 1.48s	remaining: 4.74s
238:	learn: 0.2423217	total: 1.48s	remaining: 4.73s
239:	learn: 0.2422947	total: 1.49s	remaining: 4.72s
240:	learn: 0.2422386	total: 1.5s	remaining: 4.71s
241:	learn: 0.2421664	total: 1.5s	remaining: 4.7s
242:	learn: 0.2421337	total: 1.51s	remaining: 4.69s
243:	learn: 0.2420951	total: 1.52s	remaining: 4.72s
244:	learn: 0.2420142	total: 1.53s	remaining: 4.71s
245:	learn: 0.2419634	total: 1.53s	remaining: 4.71s
246:	learn: 0.2419105	total: 1.54s	remaining: 4.7s
247:	learn: 0.2418596	total: 1.55s	remaining: 4.69s
248:	learn: 0.2418174	total: 1.55s	remaining: 4.68s
249:	learn: 0.2417674	total: 1.56s	remaining: 4.67s
250:	learn: 0.2417162	total: 1.56s	remaining: 4.66s
251:	learn: 0.2416500	total: 1.57s	remaining: 4.66s
252:	learn: 0.2416013	total: 1.57s	remaining: 4.65s
253:	learn: 0.2415422	total: 1.58s	remaining: 4.64s
254:	learn: 0.2414955	total: 1.58s	remaining: 4.63s
255:	learn: 0.2414234	total: 1.59s	remaining: 4.62s
256:	learn: 0.2413817	total: 1.6s	remaining: 4.61s
257:	learn: 0.2413173	total: 1.6s	remaining: 4.61s
258:	learn: 0.2412577	total: 1.61s	remaining: 4.6s
259:	learn: 0.2412022	total: 1.61s	remaining: 4.59s
260:	learn: 0.2411482	total: 1.62s	remaining: 4.58s
261:	learn: 0.2411115	total: 1.63s	remaining: 4.58s
262:	learn: 0.2410669	total: 1.63s	remaining: 4.57s
263:	learn: 0.2410393	total: 1.64s	remaining: 4.56s
264:	learn: 0.2410024	total: 1.64s	remaining: 4.55s
265:	learn: 0.2409546	total: 1.65s	remaining: 4.54s
266:	learn: 0.2409028	total: 1.65s	remaining: 4.54s
267:	learn: 0.2408621	total: 1.66s	remaining: 4.53s
268:	learn: 0.2408168	total: 1.66s	remaining: 4.52s
269:	learn: 0.2407550	total: 1.67s	remaining: 4.51s
270:	learn: 0.2407214	total: 1.67s	remaining: 4.5s
271:	learn: 0.2406602	total: 1.68s	remaining: 4.5s
272:	learn: 0.2406403	total: 1.69s	remaining: 4.49s
273:	learn: 0.2405979	total: 1.69s	remaining: 4.48s
274:	learn: 0.2405420	total: 1.7s	remaining: 4.47s
275:	learn: 0.2405073	total: 1.7s	remaining: 4.47s
276:	learn: 0.2404689	total: 1.71s	remaining: 4.46s
277:	learn: 0.2404078	total: 1.71s	remaining: 4.45s
278:	learn: 0.2403495	total: 1.72s	remaining: 4.44s
279:	learn: 0.2403065	total: 1.72s	remaining: 4.43s
280:	learn: 0.2402600	total: 1.73s	remaining: 4.43s
281:	learn: 0.2402180	total: 1.74s	remaining: 4.42s
282:	learn: 0.2401718	total: 1.74s	remaining: 4.41s
283:	learn: 0.2401139	total: 1.75s	remaining: 4.4s
284:	learn: 0.2400684	total: 1.75s	remaining: 4.4s
285:	learn: 0.2400060	total: 1.76s	remaining: 4.39s
286:	learn: 0.2399509	total: 1.76s	remaining: 4.38s
287:	learn: 0.2398835	total: 1.77s	remaining: 4.38s
288:	learn: 0.2398161	total: 1.78s	remaining: 4.37s
289:	learn: 0.2397655	total: 1.78s	remaining: 4.36s
290:	learn: 0.2397155	total: 1.79s	remaining: 4.36s
291:	learn: 0.2397004	total: 1.79s	remaining: 4.35s
292:	learn: 0.2396408	total: 1.8s	remaining: 4.34s
293:	learn: 0.2395797	total: 1.8s	remaining: 4.33s
294:	learn: 0.2395360	total: 1.81s	remaining: 4.33s
295:	learn: 0.2394692	total: 1.82s	remaining: 4.32s
296:	learn: 0.2394161	total: 1.82s	remaining: 4.32s
297:	learn: 0.2393624	total: 1.83s	remaining: 4.31s
298:	learn: 0.2393135	total: 1.83s	remaining: 4.3s
299:	learn: 0.2392595	total: 1.84s	remaining: 4.3s
300:	learn: 0.2391896	total: 1.85s	remaining: 4.29s
301:	learn: 0.2391496	total: 1.85s	remaining: 4.28s
302:	learn: 0.2390816	total: 1.86s	remaining: 4.28s
303:	learn: 0.2390327	total: 1.86s	remaining: 4.27s
304:	learn: 0.2389663	total: 1.87s	remaining: 4.26s
305:	learn: 0.2389007	total: 1.88s	remaining: 4.25s
306:	learn: 0.2388428	total: 1.88s	remaining: 4.25s
307:	learn: 0.2387982	total: 1.89s	remaining: 4.24s
308:	learn: 0.2387219	total: 1.89s	remaining: 4.23s
309:	learn: 0.2386827	total: 1.9s	remaining: 4.22s
310:	learn: 0.2386584	total: 1.9s	remaining: 4.22s
311:	learn: 0.2385883	total: 1.91s	remaining: 4.21s
312:	learn: 0.2385438	total: 1.91s	remaining: 4.2s
313:	learn: 0.2384858	total: 1.92s	remaining: 4.2s
314:	learn: 0.2384762	total: 1.93s	remaining: 4.19s
315:	learn: 0.2384453	total: 1.93s	remaining: 4.18s
316:	learn: 0.2383765	total: 1.94s	remaining: 4.17s
317:	learn: 0.2383111	total: 1.94s	remaining: 4.17s
318:	learn: 0.2382641	total: 1.95s	remaining: 4.16s
319:	learn: 0.2382375	total: 1.95s	remaining: 4.15s
320:	learn: 0.2381835	total: 1.96s	remaining: 4.15s
321:	learn: 0.2381411	total: 1.97s	remaining: 4.14s
322:	learn: 0.2381053	total: 1.97s	remaining: 4.13s
323:	learn: 0.2380420	total: 1.98s	remaining: 4.13s
324:	learn: 0.2380182	total: 1.98s	remaining: 4.12s
325:	learn: 0.2379679	total: 1.99s	remaining: 4.11s
326:	learn: 0.2379046	total: 1.99s	remaining: 4.1s
327:	learn: 0.2378579	total: 2s	remaining: 4.1s
328:	learn: 0.2377885	total: 2s	remaining: 4.09s
329:	learn: 0.2377398	total: 2.01s	remaining: 4.08s
330:	learn: 0.2377037	total: 2.02s	remaining: 4.08s
331:	learn: 0.2376511	total: 2.02s	remaining: 4.07s
332:	learn: 0.2376007	total: 2.03s	remaining: 4.06s
333:	learn: 0.2375654	total: 2.03s	remaining: 4.05s
334:	learn: 0.2375076	total: 2.04s	remaining: 4.05s
335:	learn: 0.2374605	total: 2.04s	remaining: 4.04s
336:	learn: 0.2374145	total: 2.05s	remaining: 4.04s
337:	learn: 0.2373671	total: 2.06s	remaining: 4.03s
338:	learn: 0.2373289	total: 2.06s	remaining: 4.02s
339:	learn: 0.2372898	total: 2.07s	remaining: 4.01s
340:	learn: 0.2372672	total: 2.08s	remaining: 4.01s
341:	learn: 0.2372231	total: 2.08s	remaining: 4s
342:	learn: 0.2371822	total: 2.09s	remaining: 4s
343:	learn: 0.2371422	total: 2.09s	remaining: 3.99s
344:	learn: 0.2370933	total: 2.1s	remaining: 3.98s
345:	learn: 0.2370287	total: 2.1s	remaining: 3.98s
346:	learn: 0.2369856	total: 2.11s	remaining: 3.97s
347:	learn: 0.2369447	total: 2.11s	remaining: 3.96s
348:	learn: 0.2369024	total: 2.12s	remaining: 3.96s
349:	learn: 0.2368565	total: 2.13s	remaining: 3.96s
350:	learn: 0.2368259	total: 2.13s	remaining: 3.95s
351:	learn: 0.2367849	total: 2.14s	remaining: 3.94s
352:	learn: 0.2367378	total: 2.15s	remaining: 3.93s
353:	learn: 0.2366982	total: 2.15s	remaining: 3.93s
354:	learn: 0.2366520	total: 2.16s	remaining: 3.92s
355:	learn: 0.2366178	total: 2.16s	remaining: 3.91s
356:	learn: 0.2365709	total: 2.17s	remaining: 3.9s
357:	learn: 0.2365272	total: 2.17s	remaining: 3.9s
358:	learn: 0.2364730	total: 2.18s	remaining: 3.89s
359:	learn: 0.2364366	total: 2.19s	remaining: 3.89s
360:	learn: 0.2363840	total: 2.19s	remaining: 3.88s
361:	learn: 0.2363479	total: 2.2s	remaining: 3.87s
362:	learn: 0.2363032	total: 2.2s	remaining: 3.87s
363:	learn: 0.2362459	total: 2.21s	remaining: 3.86s
364:	learn: 0.2361868	total: 2.21s	remaining: 3.85s
365:	learn: 0.2361220	total: 2.22s	remaining: 3.85s
366:	learn: 0.2360875	total: 2.23s	remaining: 3.84s
367:	learn: 0.2360320	total: 2.23s	remaining: 3.83s
368:	learn: 0.2359887	total: 2.24s	remaining: 3.83s
369:	learn: 0.2359455	total: 2.24s	remaining: 3.82s
370:	learn: 0.2359164	total: 2.25s	remaining: 3.81s
371:	learn: 0.2358749	total: 2.25s	remaining: 3.8s
372:	learn: 0.2358356	total: 2.26s	remaining: 3.8s
373:	learn: 0.2357957	total: 2.26s	remaining: 3.79s
374:	learn: 0.2357581	total: 2.27s	remaining: 3.78s
375:	learn: 0.2357227	total: 2.28s	remaining: 3.78s
376:	learn: 0.2356838	total: 2.28s	remaining: 3.77s
377:	learn: 0.2356528	total: 2.29s	remaining: 3.77s
378:	learn: 0.2356034	total: 2.29s	remaining: 3.76s
379:	learn: 0.2355745	total: 2.3s	remaining: 3.75s
380:	learn: 0.2355360	total: 2.3s	remaining: 3.74s
381:	learn: 0.2354722	total: 2.31s	remaining: 3.74s
382:	learn: 0.2354084	total: 2.31s	remaining: 3.73s
383:	learn: 0.2353696	total: 2.32s	remaining: 3.72s
384:	learn: 0.2353114	total: 2.33s	remaining: 3.72s
385:	learn: 0.2352986	total: 2.33s	remaining: 3.71s
386:	learn: 0.2352544	total: 2.34s	remaining: 3.7s

In [14]:
from sklearn.metrics import accuracy_score

y_pred = modelo.predict(x_test)
accuracy_score(y_test, y_pred)

0.9289666666666667

In [15]:
y_test.mean()

target    0.0709
dtype: float64